### ISSUE TITLE
Few Issues

### ISSUE THREAD

**Issue by NibblesOnGithub** [rsmacapinlac/docker-obsidian#5]
So first off, thanks for this, it does load up the latest version of Obsidian really easily and quickly. Vaults work and the like.

But I'm running into a few issues. Got BRAT installed, but cannot install The Calendarium plugin. When I go to enable it, it crashes the GUI but KASM is still running, and I cannot get back into Obsidian without a full restart. (I also just tested a few other random community plugins that don't need BRAT, and same issue)

If I accidentally close Obsidian, same scenario, I cannot reopen via right click, I have to fully restart the container.

My logs show this error. I can supply any others you might need.

```
(obsidian:467): dconf-WARNING **: 22:24:26.177: failed to commit changes to dconf: Unknown or unsupported transport “disabled” for address “disabled:”
Error: ENOENT: no such file or directory, open '/config/.config/obsidian/b4c86d48a04aea61.json'
    at Object.openSync (node:fs:601:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1869)
    at Object.readFileSync (node:fs:469:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9212)
    at /opt/Obsidian/resources/obsidian.asar/main.js:1:3390
    at R (/opt/Obsidian/resources/obsidian.asar/main.js:1:2117)
    at E (/opt/Obsidian/resources/obsidian.asar/main.js:1:3371)
    at N (/opt/Obsidian/resources/obsidian.asar/main.js:25:1074)
    at s (/opt/Obsidian/resources/obsidian.asar/main.js:25:10531)
    at IpcMainImpl.<anonymous> (/opt/Obsidian/resources/obsidian.asar/main.js:25:6510) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/config/.config/obsidian/b4c86d48a04aea61.json'
}
[467:0211/222427.468090:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[467:0211/222428.159235:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

ERROR: openbox-xdg-autostart requires PyXDG to be installed
Relaunching!
```

**Comment by rsmacapinlac** [comment]
Sorry it took a while @NibblesOnGithub, for some reason I was not getting notified. I pushed a fix up and you should be able to pull the latest image. This should fix the right-click "obsidian" issue.
